package com.msansar.ReportingAPI.enums;

public enum ErrorCode {
    DO_NOT_HONOR,
    INVALID_TRANSACTION,
    INVALID_CARD,
    NOT_SUFFICIENT_FUNDS,
    INCORRECT_PIN,
    INVALID_COUNTRY_ASSOCIATION,
    CURRENCY_NOT_ALLOWED,
    _3D_SECURE_TRANSPORT_ERROR,
    TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER
}
